### ISSUE TITLE
java.lang.NoClassDefFoundError: cn/idev/excel/FastExcel

### ISSUE THREAD

**Issue by CaoZhengxi** [CodePhiliaX/fastexcel#126]
- easyexcel和 fastexcel 共同存在 maven 引入成功
       
``` 
 <dependency>
            <groupId>cn.idev.excel</groupId>
            <artifactId>fastexcel</artifactId>
            <version>1.0.0</version>
        </dependency>
```
- 编译时存在 运行时找不到类
```
2024-12-10 21:02:56.291 [async-method-2] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler:39 - Unexpected exception occurred invoking async method: public void org.jeecg.modules.async.AsyncReport.generateReports(org.jeecg.modules.model.xml.CheckData)
java.lang.NoClassDefFoundError: cn/idev/excel/FastExcel
	at org.jeecg.modules.util.ReportUtils.excelToPdf(ReportUtils.java:89)
	at org.jeecg.modules.async.AsyncReport.xlsxToPdfProcess(AsyncReport.java:142)
	at org.jeecg.modules.async.AsyncReport.generateReports(AsyncReport.java:118)
	at org.jeecg.modules.async.AsyncReport$$FastClassBySpringCGLIB$$685e7b0d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: cn.idev.excel.FastExcel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 common frames omitted

```

**Comment by psxjoy** [comment]
The issue is most likely due to a JAR conflict. I recommend focusing your troubleshooting efforts in that area.
