### ISSUE TITLE
easypoi4.5.0和fastexcel1.0.0版本冲突

### ISSUE THREAD

**Issue by ALIFED** [CodePhiliaX/fastexcel#133]
填充word模版，需要再模版里面填充图片，这个时候会报错：
Caused by: java.lang.NoClassDefFoundError: org/apache/xmlbeans/XmlToken$Factory
	at cn.afterturn.easypoi.word.entity.MyXWPFDocument.createPicture(MyXWPFDocument.java:117)
	at com.nongxin.common.poi.excel.ExcelMapParse.addAnImage(ExcelMapParse.java:45)
	at com.nongxin.common.poi.word.ParseWord07.changeValues(ParseWord07.java:60)
	at com.nongxin.common.poi.word.ParseWord07.parseThisParagraph(ParseWord07.java:164)
	at com.nongxin.common.poi.word.ParseWord07.parseAllParagraph(ParseWord07.java:110)
	at com.nongxin.common.poi.word.ParseWord07.parseThisRow(ParseWord07.java:173)
	at com.nongxin.common.poi.word.ParseWord07.parseThisTable(ParseWord07.java:195)
	at com.nongxin.common.poi.word.ParseWord07.parseWordSetValue(ParseWord07.java:274)
	at com.nongxin.common.poi.word.ParseWord07.parseWord(ParseWord07.java:218)
	at com.nongxin.common.poi.word.MyWordExportUtil.exportWord07(MyWordExportUtil.java:30)
	at com.nongxin.check.service.modular.checkmanage.service.impl.CheckProxyInfoServiceImpl.fillTemalate(CheckProxyInfoServiceImpl.java:164)
	at com.nongxin.check.service.modular.checkmanage.service.impl.CheckProxyInfoServiceImpl.downloadProxy(CheckProxyInfoServiceImpl.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:699)
	at com.nongxin.check.service.modular.checkmanage.service.impl.CheckProxyInfoServiceImpl$$SpringCGLIB$$0.downloadProxy(<generated>)
	at com.nongxin.check.service.modular.checkmanage.controller.CheckProxyInfoController.preview(CheckProxyInfoController.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
	at com.alibaba.druid.support.spring.stat.DruidStatInterceptor.invoke(DruidStatInterceptor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
	at com.nongxin.check.service.modular.checkmanage.controller.CheckProxyInfoController$$SpringCGLIB$$0.preview(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080)

**Comment by psxjoy** [comment]
Both utility JARs depend on Apache POI. To avoid conflicts, you can explicitly specify the desired version in Maven.

**Comment by poo0054** [comment]
> fastexcel:[1.0.0]

```xml
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>5.2.5</version>
            </dependency>
```

> easypoi:[4.5.0]

https://mvnrepository.com/artifact/cn.afterturn/easypoi/4.5.0

```xml
<!-- https://mvnrepository.com/artifact/org.apache.poi/poi -->
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi</artifactId>
    <version>4.1.1</version>
</dependency>
```

您可以考虑使用`easyexcel:[3.3.4]`，它使用是`org.apache.poi:[4.1.2]`

不建议使用`easyexcel`它已经进入`维护模式`了。
